setWords()

function setWords() {
  
   const occupation = [
     "pirate",
     "samurai",
     "YouTube star",
     "chef",
     "scientist",
     "doctor",
     "teacher",
     "dancer",
     "explorer",
     "thief",
     "witch",
     "superhero",
     "robot",
     "spy",
     "president",
     "detective",
     "firefighter",
     "musician",
     "sailor",
     "journalist",
     "clown",
     "janitor",
     "martial artist",
     "wizard",
     "warrior",
     "artist",
     "computer programmer",
     "magical girl",
     "bank robber",
     "judge",
     "lawyer",
     "hunter",
     "farmer",
     "clothing designer",
     "photographer",
     "salesperson",
     "astronaut",
     "baker",
     "postal worker",
     "referee",
     "coach",
     "architect",
     "security guard",
     "student",
     "plumber",
     "dentist",
     "pilot",
     "driver",
     "actor",
     "superhero",
     "carpenter",
     "delivery person",
     "gardener",
     "hair stylist",
     "veterinarian",
     "businessperson",
     "tailor",
     "supervillain",
     "royal",
     "engineer",
     "fortune teller",
      ];

    const randomNumber3 = Math.floor(Math.random() * occupation.length);
   document.getElementById("occupation").innerHTML = occupation[randomNumber3];

}
