setWords()

function setWords() {
  const emotion = [
    "a happy",
    "a sad",
    "a surprised",
    "a scared",
    "an excited",
    "a brave",
    "a jealous",
    "a lonely",
    "a relieved",
    "a silly",
    "an uncomfortable",
    "a worried",
    "a peaceful",
    "a proud",
    "a gloomy",
    "a patient",
    "an anxious",
    "a stressed out",
    "a blissful",
    "a sweet",
    "a noble",
    "an honest",
    "a sneaky",
    "a mischievous",
    "a noble",
    "a clever",
    "a selfish",
    "an arrogant",
    "a sleepy",
    "a spoiled",
  ];
  const animal = [
    "panda",
    "dog",
    "lion",
    "cat",
    "wolf",
    "turtle",
    "zebra",
    "turtle",
    "t-rex",
    "frog",
    "seal",
    "cow",
    "gorilla",
    "dolphin",
    "deer",
    "fox",
    "camel",
    "penguin",
    "parrot",
    "kangaroo",
    "koala",
    "skunk",
    "mouse",
    "sheep",
    "eel",
    "goldfish",
    "rabbit",
    "octopus",
    "racoon",
    "red panda",
    "hedgehog",
    "velociraptor",
    "cheetah",
    "buffalo",
    "crow",
    "coyote",
    "bat",
    "platypus",
    "otter",
    "woolly mammoth",
    "elephant",
    "chicken",
    "llama",
    "narwhal",
    "hippo",
    "rhino",
    "beaver",
    "walrus",
    "pig",
    "chipmunk",
    "moose",
    "polar bear",
    "shark",
    "mole",
    "snake",
    "squirrel",
    "opossum",
    "monkey",
    "goat",
    "antelope",
    "spider",
    "butterfly",
    "bee",
    "salamander",
    "iguana",
    "jellyfish",
    "ostrich",
    "hawk",
    "duck",
    "grasshopper",
    "ladybug",
    "beetle",
    "horse",
    "crab",
    "porcupine",
    "meerkat",
    "tiger",
    "hyena",
    "chimpanzee",
    "owl",
    "armadillo",
    "swan",
    "alligator",
  ];

   const occupation = [
     "pirate",
     "samurai",
     "YouTube star",
     "chef",
     "scientist",
     "doctor",
     "teacher",
     "dancer",
     "explorer",
     "thief",
     "witch",
     "superhero",
     "robot",
     "spy",
     "president",
     "detective",
     "firefighter",
     "musician",
     "sailor",
     "journalist",
     "clown",
     "janitor",
     "martial artist",
     "wizard",
     "warrior",
     "artist",
     "computer programmer",
     "magical girl",
     "bank robber",
     "judge",
     "lawyer",
     "hunter",
     "farmer",
     "clothing designer",
     "photographer",
     "salesperson",
     "astronaut",
     "baker",
     "postal worker",
     "referee",
     "coach",
     "architect",
     "security guard",
     "student",
     "plumber",
     "dentist",
     "pilot",
     "driver",
     "actor",
     "superhero",
     "carpenter",
     "delivery person",
     "gardener",
     "hair stylist",
     "veterinarian",
     "businessperson",
     "tailor",
     "supervillain",
     "royal",
     "engineer",
      ];

  const randomNumber1 = Math.floor(Math.random() * emotion.length);
  const randomNumber2 = Math.floor(Math.random() * animal.length);
   const randomNumber3 = Math.floor(Math.random() * occupation.length);

  document.getElementById("emotion").innerHTML = emotion[randomNumber1];
  document.getElementById("animal").innerHTML = animal[randomNumber2];
   document.getElementById("occupation").innerHTML = occupation[randomNumber3];

}
